---
title: ""
about: 

 template: marquee
 links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com
---

**The following list include publications from the last two years only.** (A complete list is available on the [.pdf version of my CV.](files/cv.pdf))

Kuo SE, Atayeva R, **McGready J**, Cooney CM, Lifchez SD. (letter to the editor) Scleroderma and Raynaud Phenomenon: The Cold Truth Regarding the Use of Operative Management. <i>Plast Reconstr Surg.</i> 2023 May 10. doi: 10.1097/PRS.0000000000010423. Epub ahead of print. PMID: 37163536.

Pasqualino MM, Shaikh S, Islam MT, Parvin S, Ali H, **McGready J**, Labrique AB, Hossain MI, and Palmer AC. Household animal ownership is associated with infant animal source food consumption in Bangladesh. <i>Matern Child Nutr.</i> 2023 Mar 31:e13495. doi: 10.1111/mcn.13495. Epub ahead of print. PMID: 37002659.
  
Pasqualino MM, Shaikh S, **McGready J**, Islam MT, Ali H, Ahmed T, West KP Jr, Alam M, Hossain MI, Labrique AB,  andPalmer AC. An Egg Intervention Improves Dietary Intakes but Does Not Fill Intake Gaps for Multiple Micronutrients among Infants in Rural Bangladesh. <i>J Nutr.</i> 2023 Apr;153(4):1199-1210. doi: 10.1016/j.tjnut.2023.02.004. Epub 2023 Feb 16. PMID: 36806554..

Zale A, Abusamaan M, **McGready J**, Mathioudakis N. Prediction of Next Glucose Measurement in Hospitalized Patients by Comparing Various Regression Methods: Retrospective Cohort Study. <i>MIR Form Res</i> 2023;7:e41577 URL: https://formative.jmir.org/2023/1/e41577 DOI: 10.2196/41577

Abbey EJ, **McGready J**, Sokoll LJ, Simonsick EM, Mammen JSR. Free Thyroxine Distinguishes Subclinical Hypothyroidism From Other Aging-Related Changes in Those With Isolated Elevated Thyrotropin. <i> Front Endocrinol (Lausanne) </i>. 2022 Mar 4;13:858332. doi: 10.3389/fendo.2022.858332. PMID: 35311240; PMCID: PMC8931280.

Zale AD, Abusamaan MS,**McGready J**, Mathioudakis N. Development and validation of a machine learning model for classification of next glucose measurement in hospitalized patients. <i>EClinicalMedicine.</i> 2022 Feb 4;44:101290. doi: 10.1016/j.eclinm.2022.101290. PMID: 35169690; PMCID: PMC8829081.

Hoover-Fong J; Schulze KJ; Alade AY; Bober MB; Gough E; Hashmi SS; Hecht JT; Legare JM; Little ME; Modaff P; Pauli RM ; Rodriguez-Buritica DF; Serna ME; Smid C; Liu C; **McGready J**. Growth in Achondroplasia including stature, weight, weight-for-height and head circumference from CLARITY: Achondroplasia Natural History Study--- a multi-center retrospective cohort study of achondroplasia in the US. <i>Orphanet Journal of Rare Diseases</i>. 2021.

Sadhna V, Zegar J, Hoge C, **McGready J**, and Sidana A\*. Multiparametric MRI- ultrasound fusion prostate biopsy in patients without prior diagnosis of Prostate Cancer: Beyond Centers of Excellence. <i>The Aging Male</i>, 23:5, 1570 1575, DOI: 10.1080/13685538.2021.1873263

Beres L, Mody A, Kombatende S, Nicholas LH, Schwartz S, Eshun-Wilson I, Somwe P, Simbeza S, Pry J, Kaumba P, **McGready J**, Holmes C, Bolton-Moore C, Sikazwe I, Denison J, and Gang E. The effect of tracer contact on return-to-care among adult , "lost-to-follow-up" patients with HIV in Zambia: an instrumental variable analysis. <i>Journal of the International Aids Society</i>. 2021. 24:e25853.

Hoover-Fong JE, Alade AY, Bober MB, Hashmi S, Hecht J, Legare J, Little M, Liu K, **McGready J**, Modaff P, Pauli RM, Rodriguez-Buritica D, Schulze K, Serna E, Smid C. Achondroplasia Natural History --- a multi-center retrospective study in the US. <i>Genet Med</i>. 2021 Aug; 23(8):1498-1505

Mustafa Ali MK Sabha MM., MD, Mustafa, SK, Banifadel M, Ghazaleh S, Aburayyan, KM, Ghanim MT3; Awad MT, Gekonde, DN, Amala A;, Ramahi A, , Elzanaty, AM, Nesheiwat, Z, Shastri PM, Al-Sarie M, **McGready J**. Hospitalization and Post-hospitalization Outcomes among Teaching Internal Medicine, Employed Hospitalist and Locum Tenens Hospitalist Services in a Tertiary Center: A Prospective Cohort Study. <i>Journal of General Internal Medicine</i>. 2021.

Beres L, Schwartz S, Simbeza S, **McGready J**, Eshun-Wilson I, Mwamba C, Sikombe K, Topp S, Somwe P, Mody A, Mukamba, Ehrenkranz P, Padian N, Pry J, Moore CB, Holmes C, Sikazwe I, Denison J, and Geng E. Patterns and Predictors of Incident Return to HIV Care Among Traced, Disengaged Patients in Zambia: Analysis of a prospective cohort. <i>Journal of Acquired Immune Deficiency Syndromes (JAIDS)</i> 2021. 86(3):313-322

Abbey EJ, **McGready J**, Ferrucci, L, Simonsick E, Mammen JR. Thyroid Hormone Supplementation and All-Cause Mortality in Community-Dwelling Older Adults: Results from the Baltimore Longitudinal Study of Aging. <i>Journal of the American Geriatrics Society</i>. 2021.

Mathioudakis NN, Abusamaan MS, Shakarchi AF, Sokolinsky S, Fayzullin S, **McGready J**, Zilbermint, M, Saria,S, Golden, SH. Development and Validation of a Machine Learning Model to Predict Near-Term Risk of Iatrogenic Hypoglycemia in Hospitalized Patients.<i> JAMA Network Open</i>. 2021;4(1):e2030913. doi:10.1001/jamanetworkopen. 2020. 30913

Wood SN\*, Kennedy SR, I Akumue I , Tallam, C, Asira B, Hameeduddin Z, **McGready J**, Zimmerman L, Kennedy C, Glass N, and Decker M. Reproductive coercion among intimate partner violence survivors in Nairobi. <i>Studies in Family Planning</i>. 2020. 51(4)

Pasqualino M, Saijuddin S , Islam T, ParvinS , Ali H, , **McGready J**, Hossain I, and Palmer A. Household Livestock and Fishpond Ownership Are Associated with Consumption of Eggs, Milk, and Fish, but Not Meat, Among Infants 6--12 Months of Age in Rural Bangladesh. <i>Current Developments in Nutrition </i>. 2020 Jun; 4(Suppl 2): 884.

Merrill, K.G., Campbell, J.C., Decker, M.R. **McGready J**, Burke VM, Mwansa JK, Miti S, Frimpong C, Kennedy CE, and Denison JA. Past-Year Violence Victimization is Associated with Viral Load Failure Among HIV-Positive Adolescents and Young Adults. <i>AIDS Behav</i>. 2020. https://doi.org/10.1007/s10461-020-02958-3

Merrill KG, Campbell JC, Decker M, **McGready J**, Burke VM, Mwansa JK, Miti S, Frimpong C, Kennedy CE, and Denison JA. Prevalence of physical and sexual violence and psychological abuse among adolescents and young adults living with HIV in Zambia. <i>PLoS One</i>. 2020. Jun 25.

Hoover-Fong J, Alade AY, Ain M, Berkowitz I, Bober M, Carter E, Hecht J, Hoerschemeyer D, Krakow D, MacCarrick G, Mackenzie WG, Mendoza R, Okenfuss E, Popplewell D, Raggio C, Schulze K, **McGready J**. Blood Pressure in Adults With Short Stature Skeletal Dysplasias. <i>American Journal Medical Genetics Part A</i>. 2020 Jan;182(1):150-161.

Hoover-Fong J; Schulze KJ; Alade AY; Bober MB; Gough E; Hashmi SS; Hecht JT; Legare JM; Little ME; Modaff P; Pauli RM ; Rodriguez-Buritica DF; Serna ME; Smid C; Liu C; **McGready J**. Growth in Achondroplasia including stature, weight, weight-for-height and head circumference from CLARITY: Achondroplasia Natural History Study--- a multi-center retrospective cohort study of achondroplasia in the US. <i>Orphanet Journal of Rare Diseases</i>. 2021.

Sadhna V, Zegar J, Hoge C, **McGready J**, and Sidana A\*. Multiparametric MRI- ultrasound fusion prostate biopsy in patients without prior diagnosis of Prostate Cancer: Beyond Centers of Excellence. <i>The Aging Male</i>, 23:5, 1570 1575, DOI: 10.1080/13685538.2021.1873263

Beres L, Mody A, Kombatende S, Nicholas LH, Schwartz S, Eshun-Wilson I, Somwe P, Simbeza S, Pry J, Kaumba P, **McGready J**, Holmes C, Bolton-Moore C, Sikazwe I, Denison J, and Gang E. The effect of tracer contact on return-to-care among adult , "lost-to-follow-up" patients with HIV in Zambia: an instrumental variable analysis. <i>Journal of the International Aids Society</i>. 2021. 24:e25853.

Hoover-Fong JE, Alade AY, Bober MB, Hashmi S, Hecht J, Legare J, Little M, Liu K, **McGready J**, Modaff P, Pauli RM, Rodriguez-Buritica D, Schulze K, Serna E, Smid C. Achondroplasia Natural History --- a multi-center retrospective study in the US. <i>Genet Med</i>. 2021 Aug; 23(8):1498-1505

Mustafa Ali MK Sabha MM., MD, Mustafa, SK, Banifadel M, Ghazaleh S, Aburayyan, KM, Ghanim MT3; Awad MT, Gekonde, DN, Amala A;, Ramahi A, , Elzanaty, AM, Nesheiwat, Z, Shastri PM, Al-Sarie M, **McGready J**. Hospitalization and Post-hospitalization Outcomes among Teaching Internal Medicine, Employed Hospitalist and Locum Tenens Hospitalist Services in a Tertiary Center: A Prospective Cohort Study. <i>Journal of General Internal Medicine</i>. 2021.

Beres L, Schwartz S, Simbeza S, **McGready J**, Eshun-Wilson I, Mwamba C, Sikombe K, Topp S, Somwe P, Mody A, Mukamba, Ehrenkranz P, Padian N, Pry J, Moore CB, Holmes C, Sikazwe I, Denison J, and Geng E. Patterns and Predictors of Incident Return to HIV Care Among Traced, Disengaged Patients in Zambia: Analysis of a prospective cohort. <i>Journal of Acquired Immune Deficiency Syndromes (JAIDS)</i> 2021. 86(3):313-322

Abbey EJ, **McGready J**, Ferrucci, L, Simonsick E, Mammen JR. Thyroid Hormone Supplementation and All-Cause Mortality in Community-Dwelling Older Adults: Results from the Baltimore Longitudinal Study of Aging. <i>Journal of the American Geriatrics Society</i>. 2021.

Mathioudakis NN, Abusamaan MS, Shakarchi AF, Sokolinsky S, Fayzullin S, **McGready J**, Zilbermint, M, Saria,S, Golden, SH. Development and Validation of a Machine Learning Model to Predict Near-Term Risk of Iatrogenic Hypoglycemia in Hospitalized Patients.<i> JAMA Network Open</i>. 2021;4(1):e2030913. doi:10.1001/jamanetworkopen. 2020. 30913

Wood SN\*, Kennedy SR, I Akumue I , Tallam, C, Asira B, Hameeduddin Z, **McGready J**, Zimmerman L, Kennedy C, Glass N, and Decker M. Reproductive coercion among intimate partner violence survivors in Nairobi. <i>Studies in Family Planning</i>. 2020. 51(4)

Pasqualino M, Saijuddin S , Islam T, ParvinS , Ali H, , **McGready J**, Hossain I, and Palmer A. Household Livestock and Fishpond Ownership Are Associated with Consumption of Eggs, Milk, and Fish, but Not Meat, Among Infants 6--12 Months of Age in Rural Bangladesh. <i>Current Developments in Nutrition </i>. 2020 Jun; 4(Suppl 2): 884.

Merrill, K.G., Campbell, J.C., Decker, M.R. **McGready J**, Burke VM, Mwansa JK, Miti S, Frimpong C, Kennedy CE, and Denison JA. Past-Year Violence Victimization is Associated with Viral Load Failure Among HIV-Positive Adolescents and Young Adults. <i>AIDS Behav</i>. 2020. https://doi.org/10.1007/s10461-020-02958-3

Merrill KG, Campbell JC, Decker M, **McGready J**, Burke VM, Mwansa JK, Miti S, Frimpong C, Kennedy CE, and Denison JA. Prevalence of physical and sexual violence and psychological abuse among adolescents and young adults living with HIV in Zambia. <i>PLoS One</i>. 2020. Jun 25.

Hoover-Fong J, Alade AY, Ain M, Berkowitz I, Bober M, Carter E, Hecht J, Hoerschemeyer D, Krakow D, MacCarrick G, Mackenzie WG, Mendoza R, Okenfuss E, Popplewell D, Raggio C, Schulze K, **McGready J**. Blood Pressure in Adults With Short Stature Skeletal Dysplasias. <i>American Journal Medical Genetics Part A</i>. 2020 Jan;182(1):150-161.

Beres L, Merrill K, **McGready J**, Denison J, Scwartz S, Sikazwe I, and Decker M. Intimate partner violence polyvictimisation and HIV among coupled women in Zambia: Analysis of a population-based survey. <i>Global Health</i>. 2020 Apr;15(4):558-570.
